version: "3"
services: 
  api:
    container_name: api
    restart: always
    build: ./api
    env_file:
      - ./api/.env
    ports:
      - "8000:8000"
  socket:
    container_name: socket
    restart: always
    build: ./socket
    ports:
      - "5000:5000"
  admin_frontend:
    container_name: admin_frontend
    restart: always
    build: ./admin_frontend
    env_file:
      - ./admin_frontend/.env
    ports:
      - "3001:3001"
  users_frontend:
    container_name: users_frontend
    restart: always
    build: ./users_frontend
    env_file:
      - ./users_frontend/.env
    ports:
      - "3000:3000"
    links:
      - socket