version: "3"
services: 
  api:
    container_name: api
    restart: always
    build: ./src/api
    env_file:
      - ./.env
    ports:
      - "8000:8000"
  admin-frontend:
    container_name: admin_frontend
    restart: always
    build: ./src/frontend/admin
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "5000:5000"